spring:
  datasource:
    druid:
      #登录的密码设置
      stat-view-servlet:
        loginUsername: admin
        loginPassword: 123456
    dynamic:
      druid: #以下是全局默认值，可以全局更改
        initial-size:
        max-active:
        min-idle:
        max-wait:
      datasource:
        master:
          username: root
          password: Tlz19970905
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.98.253.2:3306/test1?characterEncoding=utf8&useSSL=false
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size:
            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter。
        slave:
          username: root
          password: Tlz19970905
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.98.253.2:3306/test2?characterEncoding=utf8&useSSL=false
          druid: # 以下参数针对每个库可以重新设置druid参数
            initial-size:
            validation-query: select 1 FROM DUAL #比如oracle就需要重新设置这个
            public-key: #（非全局参数）设置即表示启用加密,底层会自动帮你配置相关的连接参数和filter。
#           ......
