server:
  port: 8883

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: dynamic-dataSource
          uri: lb://dynamic-dataSource
          predicates:
           - Path=/sw/**
          filters:
#           - SwaggerHeaderFilter
           - StripPrefix=1
        - id: provider
          #\u5176\u4ED6\u670D\u52A1\u540D
          uri: lb://provider
          #\u4EE5aaa\u5F00\u5934\u7684url\u5C06\u4F1A\u8BF7\u6C42provider\u670D\u52A1\u5BF9\u5E94\u7684\u63A5\u53E3
          predicates:
            - Path=/aaa/**
          filters:
          #\u8F6C\u53D1\u4E4B\u524D\u53BB\u9664\u4E00\u7EA7\u524D\u7F00
            - StripPrefix=1
          #\u81EA\u5B9A\u4E49\u8BF7\u6C42\u8DEF\u5F84
        - id: juejin
          uri: https://juejin.im/user/5aa50b96f265da23866f836e
          predicates:
            - Path=/juejin/**
          filters:
              - StripPrefix=1
    discovery:
      locator:
        enabled: false
        lowerCaseServiceId: true
#eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:7082/eureka/
#  spring.cloud.gateway.discovery.locator.enabled\uFF1A
#  \u662F\u5426\u4E0E\u670D\u52A1\u6CE8\u518C\u4E8E\u53D1\u73B0\u7EC4\u4EF6\u8FDB\u884C\u7ED3\u5408\uFF0C\u901A\u8FC7 serviceId \u8F6C\u53D1\u5230\u5177\u4F53\u7684\u670D\u52A1\u5B9E\u4F8B\u3002\u9ED8\u8BA4\u4E3A false\uFF0C\u8BBE\u4E3A true \u4FBF\u5F00\u542F\u901A\u8FC7\u670D\u52A1\u4E2D\u5FC3\u7684\u81EA\u52A8\u6839\u636E serviceId \u521B\u5EFA\u8DEF\u7531\u7684\u529F\u80FD\u3002
#  pring.cloud.gateway.discovery.locator.lowerCaseServiceId\uFF1A
#  \u662F\u5C06\u8BF7\u6C42\u8DEF\u5F84\u4E0A\u7684\u670D\u52A1\u540D\u914D\u7F6E\u4E3A\u5C0F\u5199\uFF08\u56E0\u4E3A\u670D\u52A1\u6CE8\u518C\u7684\u65F6\u5019\uFF0C\u5411\u6CE8\u518C\u4E2D\u5FC3\u6CE8\u518C\u65F6\u5C06\u670D\u52A1\u540D\u8F6C\u6210\u5927\u5199\u7684\u4E86\uFF09