spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://47.98.253.2:3306/test2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: root
    password: Tlz19970905
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1500000
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      maximum-pool-size: 8
