spring:
  datasource:
    dynamic:
      hikari:  # 全局hikariCP参数，所有值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        catalog:
        connection-timeout:
        validation-timeout:
        idle-timeout:
        leak-detection-threshold:
        max-lifetime:
        max-pool-size:
      datasource:
        master:
          username: root
          password: Tlz19970905
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://47.98.253.2:3306/master?characterEncoding=utf8&useSSL=false
          hikari: # 以下参数针对每个库可以重新设置hikari参数
            max-pool-size:
            idle-timeout:
        #           ......
        slave:
          username: root
          password: Tlz19970905
          url: jdbc:mysql://47.98.253.2:3306/slave?characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 6
