spring:
  profiles:
    active: hikariCP
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    typeEnumsPackage: com.aaa.mybatisplus.enums
    global-config:
      db-config:
        logic-delete-field: is_del  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
        logic-delete-value: 1 # 逻辑已删除值(默认为 1)
        logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
server:
  worker-id: 5
  data-center-id: 6
  port: 7070
