spring:
  profiles:
    active: hikariCP
#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    typeEnumsPackage: com.aaa.mybatisplus.enums
server:
  worker-id: 5
  data-center-id: 6
  port: 7070
