package com.aaa.dynamicdatadbstx.dao;


import com.aaa.dynamicdatadbstx.entity.A;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insertSelective(A record);
}
