package com.aaa.dynamic_data_mybatis.dao;

import com.aaa.dynamic_data_mybatis.entity.A;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insertSelective(A record);
}