package com.aaa.dynamic_data_mybatis.dao;

import com.aaa.dynamic_data_mybatis.entity.A;
import com.aaa.dynamic_data_mybatis.entity.AExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    long countByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int deleteByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insertSelective(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    List<A> selectByExample(AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") A record, @Param("example") AExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") A record, @Param("example") AExample example);
}