package com.aaa.dynamic_data_mybatis.dao;

import com.aaa.dynamic_data_mybatis.entity.ZeusOrgRole;

public interface ZeusOrgRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insert(ZeusOrgRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table a
     *
     * @mbg.generated
     */
    int insertSelective(ZeusOrgRole record);
}