package com.aaa.dynamic_data_mybatis.entity;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table a
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class A implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.a
     *
     * @mbg.generated
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.b
     *
     * @mbg.generated
     */
    private Integer b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table a
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.a
     *
     * @return the value of a.a
     *
     * @mbg.generated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.a
     *
     * @param a the value for a.a
     *
     * @mbg.generated
     */
    public void setA(String a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.b
     *
     * @return the value of a.b
     *
     * @mbg.generated
     */
    public Integer getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.b
     *
     * @param b the value for a.b
     *
     * @mbg.generated
     */
    public void setB(Integer b) {
        this.b = b;
    }
}